export const startPos = [
    {x: 1, y: 8, piece: "br"},
    {x: 2, y: 8, piece: "bb"},
    {x: 3, y: 8, piece: "bn"},
    {x: 4, y: 8, piece: "bq"},
    {x: 5, y: 8, piece: "bk"},
    {x: 6, y: 8, piece: "bn"},
    {x: 7, y: 8, piece: "bb"},
    {x: 8, y: 8, piece: "br"},
    {x: 1, y: 7, piece: "bp"},
    {x: 2, y: 7, piece: "bp"},
    {x: 3, y: 7, piece: "bp"},
    {x: 4, y: 7, piece: "bp"},
    {x: 5, y: 7, piece: "bp"},
    {x: 6, y: 7, piece: "bp"},
    {x: 7, y: 7, piece: "bp"},
    {x: 8, y: 7, piece: "bp"},
    {x: 1, y: 6},
    {x: 2, y: 6},
    {x: 3, y: 6},
    {x: 4, y: 6},
    {x: 5, y: 6},
    {x: 6, y: 6},
    {x: 7, y: 6},
    {x: 8, y: 6},
    {x: 1, y: 5},
    {x: 2, y: 5},
    {x: 3, y: 5},
    {x: 4, y: 5},
    {x: 5, y: 5},
    {x: 6, y: 5},
    {x: 7, y: 5},
    {x: 8, y: 5},
    {x: 1, y: 4},
    {x: 2, y: 4},
    {x: 3, y: 4},
    {x: 4, y: 4},
    {x: 5, y: 4},
    {x: 6, y: 4},
    {x: 7, y: 4},
    {x: 8, y: 4},
    {x: 1, y: 3},
    {x: 2, y: 3},
    {x: 3, y: 3},
    {x: 4, y: 3},
    {x: 5, y: 3},
    {x: 6, y: 3},
    {x: 7, y: 3},
    {x: 8, y: 3},
    {x: 1, y: 2, piece: "wp"},
    {x: 2, y: 2, piece: "wp"},
    {x: 3, y: 2, piece: "wp"},
    {x: 4, y: 2, piece: "wp"},
    {x: 5, y: 2, piece: "wp"},
    {x: 6, y: 2, piece: "wp"},
    {x: 7, y: 2, piece: "wp"},
    {x: 8, y: 2, piece: "wp"},
    {x: 1, y: 1, piece: "wr"},
    {x: 2, y: 1, piece: "wb"},
    {x: 3, y: 1, piece: "wn"},
    {x: 4, y: 1, piece: "wq"},
    {x: 5, y: 1, piece: "wk"},
    {x: 6, y: 1, piece: "wn"},
    {x: 7, y: 1, piece: "wb"},
    {x: 8, y: 1, piece: "wr"},

]

